/**
 * MOMENTKU PLATFORM ENGINE
 * OWNERSHIP: PLATFORM ENGINEERING TEAM
 * MATURITY: PRODUCTION / COMPANY-GRADE
 * WARNING: CHANGES REQUIRE ARCHITECT REVIEW
 */


const required = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "MIDTRANS_SERVER_KEY",
  "NEXT_PUBLIC_MIDTRANS_CLIENT_KEY",
  "CRON_SECRET",
];
required.forEach((key) => {
  if (!process.env[key]) {
    throw new Error(`ENV MISSING: ${key}`);
  }
});
